### ISSUE TITLE
Everytime a connection is closed an Exception is thrown

### ISSUE THREAD

**Issue by marl0rd** [marlontrujillo1080/eru#62]
The exception:

```
java.io.IOException: Stream closed
	at java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:170)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:291)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at java.io.DataInputStream.read(DataInputStream.java:149)
	at net.wimpi.modbus.io.ModbusTCPTransport.readResponse(ModbusTCPTransport.java:171)
	at net.wimpi.modbus.io.ModbusTCPTransaction.execute(ModbusTCPTransaction.java:193)
	at org.assemblits.eru.comm.context.MessageToReadAddressBlock.send(MessageToReadAddressBlock.java:78)
	at org.assemblits.eru.comm.member.ModbusDeviceCommunicator.communicate(ModbusDeviceCommunicator.java:50)
	at org.assemblits.eru.comm.member.Director.run(Director.java:24)
	at java.lang.Thread.run(Thread.java:748)
net.wimpi.modbus.ModbusIOException: Executing transaction failed (tried 3 times)
	at net.wimpi.modbus.io.ModbusTCPTransaction.execute(ModbusTCPTransaction.java:197)
	at org.assemblits.eru.comm.context.MessageToReadAddressBlock.send(MessageToReadAddressBlock.java:78)
	at org.assemblits.eru.comm.member.ModbusDeviceCommunicator.communicate(ModbusDeviceCommunicator.java:50)
	at org.assemblits.eru.comm.member.Director.run(Director.java:24)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by marl0rd** [comment]
This is something related with the Jamod Library and the way is handled the tags. All tags are always watching if the connection is activated to be updated, so if someone deactivate a connection the tag will stop updating but while stop updating some polls are going to fail... Almost natural but awkward.

**Comment by marl0rd** [comment]
There is a bug ticket in the library forum:
[link](https://sourceforge.net/p/jamod/bugs/53/)

**Comment by marl0rd** [comment]
Thinking about changing Jamod by J2mod:
[j2mod](https://github.com/steveohara/j2mod)

**Comment by marl0rd** [comment]
Jamod replaced successfully
